var tree = [["Adamgoose",,"",
                [["Gitlab","Adamgoose\/Gitlab.html","",
                [["Models","Adamgoose\/Gitlab\/Models.html","",
                [["BaseModel","Adamgoose\/Gitlab\/Models\/BaseModel.html"," < Client",
                [        ]],["Blob","Adamgoose\/Gitlab\/Models\/Blob.html"," < BaseModel",
                [        ]],["Branch","Adamgoose\/Gitlab\/Models\/Branch.html"," < BaseModel",
                [        ]],["Commit","Adamgoose\/Gitlab\/Models\/Commit.html"," < BaseModel",
                [        ]],["Diff","Adamgoose\/Gitlab\/Models\/Diff.html"," < BaseModel",
                [        ]],["Event","Adamgoose\/Gitlab\/Models\/Event.html"," < BaseModel",
                [        ]],["Group","Adamgoose\/Gitlab\/Models\/Group.html"," < BaseModel",
                [        ]],["Hook","Adamgoose\/Gitlab\/Models\/Hook.html"," < BaseModel",
                [        ]],["Issue","Adamgoose\/Gitlab\/Models\/Issue.html"," < BaseModel",
                [        ]],["Key","Adamgoose\/Gitlab\/Models\/Key.html"," < BaseModel",
                [        ]],["MergeRequest","Adamgoose\/Gitlab\/Models\/MergeRequest.html"," < BaseModel",
                [        ]],["Milestone","Adamgoose\/Gitlab\/Models\/Milestone.html"," < BaseModel",
                [        ]],["Note","Adamgoose\/Gitlab\/Models\/Note.html"," < BaseModel",
                [        ]],["Project","Adamgoose\/Gitlab\/Models\/Project.html"," < BaseModel",
                [        ]],["Snippet","Adamgoose\/Gitlab\/Models\/Snippet.html"," < BaseModel",
                [        ]],["Tag","Adamgoose\/Gitlab\/Models\/Tag.html"," < BaseModel",
                [        ]],["Tree","Adamgoose\/Gitlab\/Models\/Tree.html"," < BaseModel",
                [        ]],["User","Adamgoose\/Gitlab\/Models\/User.html"," < BaseModel",
                [        ]]        ]],["Client","Adamgoose\/Gitlab\/Client.html","",
                [        ]],["GitlabServiceProvider","Adamgoose\/Gitlab\/GitlabServiceProvider.html"," < ServiceProvider",
                [        ]]        ]]        ]]        ]

