<?php

return [

  /*
  |--------------------------------------------------------------------------
  | Gitlab Instance Host Name
  |--------------------------------------------------------------------------
  |
  | Here is where you define where we can access your installation of
  | GitLab CE. For instance, if you access your GitLab instance by
  | browsing to http://git.example.com, enter "git.example.com"
  |
  */
  'hostname'      => 'YOUR_GITLAB_HOSTNAME',

  /*
  |--------------------------------------------------------------------------
  | Use SSL
  |--------------------------------------------------------------------------
  |
  | Depending on whether or not you have an SSL certificate installed
  | on your GitLab CE server, we need to access the API via either
  | http or https. Enter true to use https or false to use http
  |
  */
  'secure'        => true,

  /*
  |--------------------------------------------------------------------------
  | API Version
  |--------------------------------------------------------------------------
  |
  | Your GitLab CE instance's API version can be revealed by
  | browsing to https://git.example.com/admin/. Enter the
  | proper API version here so we access the right API
  |
  */
  'api_version'   => 'v3',

  /*
  |--------------------------------------------------------------------------
  | Private Token
  |--------------------------------------------------------------------------
  |
  | The GitLab API requires authentication by way of a private token in
  | order to access the API. A token can be generated by browsing to
  | https://git.example.com/profile/account when you're logged in
  |
  */
  'private_token' => 'YOUR_PRIVATE_TOKEN',

];