<?php

return [

  /*
  |--------------------------------------------------------------------------
  | Gitlab Instance Host Name
  |--------------------------------------------------------------------------
  |
  | Here is where you define where we can access your installation of
  | GitLab CE. For instance, if you access your GitLab instance by
  | browsing to http://git.example.com, enter "git.example.com"
  |
  */
  'hostname'      => 'YOUR_GITLAB_HOSTNAME',

  /*
  |--------------------------------------------------------------------------
  | Use SSL
  |--------------------------------------------------------------------------
  |
  | Depending on whether or not you have an SSL certificate installed
  | on your GitLab CE server, we need to access the API via either
  | http or https. Enter true to use https or false to use http
  |
  */
  'secure'        => true,

  /*
  |--------------------------------------------------------------------------
  | API Version
  |--------------------------------------------------------------------------
  |
  | Your GitLab CE instance's API version can be revealed by
  | browsing to https://git.example.com/admin/. Enter the
  | proper API version here so we access the right API
  |
  */
  'api_version'   => 'v3',

  /*
  |--------------------------------------------------------------------------
  | Private Token
  |--------------------------------------------------------------------------
  |
  | The GitLab API requires authentication by way of a private token in
  | order to access the API. A token can be generated by browsing to
  | https://git.example.com/profile/account when you're logged in
  |
  */
  'private_token' => 'YOUR_PRIVATE_TOKEN',

  /*
  |--------------------------------------------------------------------------
  | Class Aliases
  |--------------------------------------------------------------------------
  |
  | Since the API's classes have a long and annoying namespace, and since
  | you probably don't want to manually alias each all these yourself,
  | I've done it here, and made it simple for you to customize them
  |
  */
  'aliases' => [
  // Alias (change)       =>  Target (don't change)
    'Gitlab'              => 'Adamgoose\Gitlab\Client',
    'Gitlab\Blob'         => 'Adamgoose\Gitlab\Models\Blob',
    'Gitlab\Branch'       => 'Adamgoose\Gitlab\Models\Branch',
    'Gitlab\Commit'       => 'Adamgoose\Gitlab\Models\Commit',
    'Gitlab\Diff'         => 'Adamgoose\Gitlab\Models\Diff',
    'Gitlab\Event'        => 'Adamgoose\Gitlab\Models\Event',
    'Gitlab\Group'        => 'Adamgoose\Gitlab\Models\Group',
    'Gitlab\Hook'         => 'Adamgoose\Gitlab\Models\Hook',
    'Gitlab\Issue'        => 'Adamgoose\Gitlab\Models\Issue',
    'Gitlab\Key'          => 'Adamgoose\Gitlab\Models\Key',
    'Gitlab\MergeRequest' => 'Adamgoose\Gitlab\Models\MergeRequest',
    'Gitlab\Milestone'    => 'Adamgoose\Gitlab\Models\Milestone',
    'Gitlab\Note'         => 'Adamgoose\Gitlab\Models\Note',
    'Gitlab\Project'      => 'Adamgoose\Gitlab\Models\Project',
    'Gitlab\Snippet'      => 'Adamgoose\Gitlab\Models\Snippet',
    'Gitlab\Tag'          => 'Adamgoose\Gitlab\Models\Tag',
    'Gitlab\Tree'         => 'Adamgoose\Gitlab\Models\Tree',
    'Gitlab\User'         => 'Adamgoose\Gitlab\Models\User',
  ],
];